local Transf = require("transf")

function data()
    return {
        cost = {
            price = 10000,
        },
        category = {
            categories = { "decoration", },
        },
        description = {
            name = _("station_clock"),
		    description = _("ceiling_mountable"),
		    icon = "ui/construction/station/rail/motras/decoration_clock_ceiling_mounted_era_c.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "motras_decoration_ceiling_mounted",
        order = {
            value = 1,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local decoration = result.motras:register(slotId)

            decoration:handle(function ()
                table.insert(result.models, {
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = Transf.mul(transform, Transf.scale({x = 0.5, y = -0.5, z = -1.0})),
                    tag = tag
                })
                table.insert(result.models, {
                    id = "station/rail/asset/era_c_small_clock.mdl",
                    transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0.0, y = 0.0, z = -0.8})),
                    tag = tag
                })
            end)
        end,
        getModelsFn = function()
            return {
                { 
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = {
                        0.5, 0, 0, 0,
                        0, -0.5, 0, 0,
                        0, 0, -1.0, 0,
                        0, 0, 0, 1
                    },
                }, { 
                    id = "station/rail/asset/era_c_small_clock.mdl",
                    transf = {
                        0, -1.0, 0, 0,
                        1.0, 0, 0, 0,
                        0, 0, 1.0, 0,
                        0, 0, -0.8, 1
                    },
                },
            }
        end
    }
end