local PlatformModuleUtils = require('motras_platformmoduleutils')
local t = require('motras_types')
local Box = require('motras_box')
local Transf = require('transf')

function data()
    return {
        cost = {
            price = 18000,
        },
        category = {
            categories = { "passenger", },
        },
        description = {
            name = _("platform_270"),
		    description = _("platform_270_desc"),
            icon = "ui/construction/station/rail/modular_station/track.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "motras_platform",
        order = {
            value = 1,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local platform = result.motras:register(slotId, {platformHeight = 0.27})
            PlatformModuleUtils.addBuildingSlotsFor40mPlatform(platform, result.slots)

            platform:handle(function (moduleResult)
                local boundingBox = Box:new(
                    {platform:getAbsoluteX() - 20, platform:getAbsoluteY() - 2.5, 0},
                    {platform:getAbsoluteX() + 20, platform:getAbsoluteY() + 2.5, platform:getAbsolutePlatformHeight()}
                )

                table.insert(result.terrainAlignmentLists, { type = "EQUAL", faces = { boundingBox:getGroundFace() } })

                PlatformModuleUtils.makePlatform(
                    platform,
                    result.models,
                    'station/rail/motras/platform_rep.mdl',
                    'station/rail/motras/platform_edge_rep.mdl',
                    'station/rail/motras/platform_back_rep.mdl',
                    'station/rail/motras/platform_side.mdl',
                    'station/rail/motras/platform_edge_side_left.mdl',
                    'station/rail/motras/platform_edge_side_right.mdl',
                    'station/rail/motras/platform_back_side_left.mdl',
                    'station/rail/motras/platform_back_side_right.mdl',
                    { addBackEdgesOnConnect = true }
                )

                table.insert(result.models, {
                    id =  'station/rail/motras/path/passenger_platform_40m.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        platform:getAbsoluteX(), platform:getAbsoluteY(), platform:getAbsolutePlatformHeight(), 1
                    }
                })
            end)
        end,
        getModelsFn = function()
            return { }
        end
    }
end