local TrackModuleUtils = require('motras_trackmoduleutils')

function data()
    return {
        cost = {
            price = 18000,
        },
        category = {
            categories = { "tracks", },
        },
        description = {
            name = _("High-speed tracks"),
		description = _("Specialized tracks for higher speeds."),
            icon = "ui/construction/station/rail/modular_station/high_speed.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "motras_track",
        order = {
            value = 3,
        },
        metadata = {
            passenger = true,
            --track = true
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local track = result.motras:register(slotId)
            track:handle(function (moduleResult)
                local snapLeft = not track:getGrid():has(track:getGridX() - 1, track:getGridY())
                local snapRight = not track:getGrid():has(track:getGridX() + 1, track:getGridY())
                TrackModuleUtils.makeTrack(track, 'high_speed.lua', false, snapLeft, snapRight)
            end)
        end,
        getModelsFn = function()
            return { }
        end
    }
end