local Transf = require("transf")

function data()
    return {
        cost = {
            price = 10000,
        },
        category = {
            categories = { "decoration", },
        },
        description = {
            name = _("benches_and_trashcan"),
		    description = _("placeable_on_platforms"),
		    icon = "ui/construction/station/rail/motras/decoration_benches_and_trashbin_era_c.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "motras_decoration_asset",
        order = {
            value = 19002,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local asset = result.motras:register(slotId)

            asset:handle(function ()
                local gridElement = asset:getParentGridElement()

                if asset:getId() >= 41 and asset:getId() <= 44 then
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_double_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = -2, y = 0, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_double_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 2, y = 0, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_trashcan.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0, y = 0, z = -1})),
                        tag = tag
                    })
                elseif not gridElement:hasNeighborTop() and gridElement:getNeighborBottom():isTrack() then
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = -2, y = 2.1, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 2, y = 2.1, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_trashcan.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0, y = 1.95, z = -1})),
                        tag = tag
                    })
                elseif not gridElement:hasNeighborBottom() and gridElement:getNeighborTop():isTrack() then
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(-math.pi / 2, {x = -2, y = -2.1, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(-math.pi / 2, {x = 2, y = -2.1, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_trashcan.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(-math.pi / 2, {x = 0, y = -1.95, z = -1})),
                        tag = tag
                    })
                elseif gridElement:hasAsset(asset:getId() - 8) then
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(-math.pi / 2, {x = -2, y = 0.4, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(-math.pi / 2, {x = 2, y = 0.4, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_trashcan.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(-math.pi / 2, {x = 0, y = 0.55, z = -1})),
                        tag = tag
                    }) 
                elseif gridElement:getNeighborTop():hasAsset(asset:getId() - 8) then
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = -2, y = -0.4, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_single_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 2, y = -0.4, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_trashcan.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0, y = -0.55, z = -1})),
                        tag = tag
                    }) 
                else
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_double_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = -2, y = 0, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_double_chair.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 2, y = 0, z = -1})),
                        tag = tag
                    })
                    table.insert(result.models, {
                        id = "station/rail/asset/era_c_trashcan.mdl",
                        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0, y = 0, z = -1})),
                        tag = tag
                    }) 
                end
                
            end)
        end,
        getModelsFn = function()
            return {
                { 
                    id = "station/rail/asset/era_c_double_chair.mdl",
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        -2, 0, 0, 1
                    },
                }, { 
                    id = "station/rail/asset/era_c_double_chair.mdl",
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        2, 0, 0, 1
                    },
                }, { 
                    id = "station/rail/asset/era_b_trashcan.mdl",
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1
                    },
                },
            }
        end
    }
end