local TrackModuleUtils = require('motras_trackmoduleutils')

function data()
    return {
        cost = {
            price = 18000,
        },
        category = {
            categories = { "tracks", },
        },
        description = {
            name = _("custom_track_standard"),
		    description = _("selectable_in_options_menu") .. "\n" .. _("not_electrified"),
            icon = "ui/construction/station/rail/modular_station/track.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 1849 --commonapi and 0 or 1849
        },
        type = "motras_track",
        order = {
            value = 5,
        },
        metadata = {
            motras = {
                electrified = false,
                highspeed = false,
                toggleElectrificationTo = "station/rail/modules/motras_track_train_custom_1_catenary.module",
                toggleHighspeedTo = "station/rail/modules/motras_track_train_custom_2.module"
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local track = result.motras:register(slotId)
            track:handle(function (moduleResult)
                local snapLeft = not track:getGrid():has(track:getGridX() - 1, track:getGridY())
                local snapRight = not track:getGrid():has(track:getGridX() + 1, track:getGridY())
                TrackModuleUtils.makeTrack(track, result.motras:getCustomTrack1(), false, snapLeft, snapRight)
            end)
        end,
        getModelsFn = function()
            return { }
        end
    }
end