local Transf = require("transf")

function data()
    return {
        cost = {
            price = 0,
        },
        category = {
            categories = { "decoration", },
        },
        description = {
            name = _("station_clock") .. " " .. _("motras_large"),
		    description = _("wall_mountable"),
		    icon = "ui/construction/station/rail/motras/decoration_clock_wall_mounted_large_era_c.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "motras_wall_mounted_decoration",
        order = {
            value = 59101,
        },
        metadata = {
            motras = {
                theme = "era_c",
                themeType = "clock_large_wall_mounted"
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local decoration = result.motras:register(slotId)

            decoration:handle(function ()
                table.insert(result.models, {
                    id = "station/rail/asset/era_c_big_clock.mdl",
                    transf = transform,
                    tag = tag
                })
            end)
        end,
        getModelsFn = function()
            return {
                { 
                    id = "station/rail/asset/era_c_big_clock.mdl",
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1
                    },
                },
            }
        end
    }
end