local TrackModuleUtils = require('motras_trackmoduleutils')

function data()
    return {
        cost = {
            price = 18000,
        },
        category = {
            categories = { "tracks", },
        },
        description = {
            name = _("Standard tracks"),
            description = _("Standard tracks with limited speed capabilities."),
            icon = "ui/construction/station/rail/modular_station/track.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "motras_track",
        order = {
            value = 1,
        },
        metadata = {
            motras_electrified = false,
            motras_highspeed = false,
            motras_toggleElectrificationTo = "station/rail/modules/motras_track_train_normal_catenary.module",
            motras_toggleHighspeedTo = "station/rail/modules/motras_track_train_high_speed.module",
            motras_speedLimit = 120.0 / 3.6,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local track = result.motras:register(slotId)
            TrackModuleUtils.addFenceSlots(track, result.slots)
            
            track:handle(function (moduleResult)
                TrackModuleUtils.makeLot(result, track)

                local snapLeft = not track:getGrid():has(track:getGridX() - 1, track:getGridY())
                local snapRight = not track:getGrid():has(track:getGridX() + 1, track:getGridY())
                TrackModuleUtils.makeTrack(track, 'standard.lua', false, snapLeft, snapRight)
            end)
        end,
        getModelsFn = function()
            return { }
        end
    }
end