local Transf = require("transf")
local ModelUtils = require('motras_modelutils')

function data()
    return {
        cost = {
            price = 10000,
        },
        category = {
            categories = { "decoration", },
        },
        description = {
            name = _("platform_number_sign"),
		    description = _("ceiling_mountable"),
		    icon = "ui/construction/station/rail/motras/decoration_platform_numbers_ceiling_mounted_era_c.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "motras_decoration_ceiling_mounted",
        order = {
            value = 1,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local decoration = result.motras:register(slotId)

            decoration:handle(function ()
                table.insert(result.models, {
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = Transf.mul(transform, Transf.scale({x = 0.5, y = -0.5, z = -1.0}))
                })

                local label = ''
                local gridElement = decoration:getParentGridElement()
                local neighborTop = gridElement:getNeighborTop()
                local neighborBottom = gridElement:getNeighborBottom()

                if decoration:getId() % 2 == 1 and neighborTop:isTrack() then
                    label = neighborTop:getDisplayedId()
                elseif decoration:getId() % 2 == 0 and neighborBottom:isTrack() then
                    label = neighborBottom:getDisplayedId()
                end
                ModelUtils.addLabeledModel(
                    result,
                    "station/rail/motras/platform_number_sign_era_c.mdl",
                    { label, label },
                    Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0.0, y = 0.0, z = -0.8})),
                    tag
                )
            end)
        end,
        getModelsFn = function()
            return {
                { 
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = {
                        0.5, 0, 0, 0,
                        0, -0.5, 0, 0,
                        0, 0, -1.0, 0,
                        0, 0, 0, 1
                    },
                }, { 
                    id = "station/rail/motras/platform_number_sign_era_c.mdl",
                    transf = {
                        0, -1.0, 0, 0,
                        1.0, 0, 0, 0,
                        0, 0, 1.0, 0,
                        0, 0, -0.8, 1
                    },
                },
            }
        end
    }
end