local TrackModuleUtils = require('motras_trackmoduleutils')

function data()
    return {
        cost = {
            price = 18000,
        },
        category = {
            categories = { "tracks", },
        },
        description = {
            name = _("High-speed tracks with catenary"),
            description = _("Specialized tracks with catenary for higher speeds."),
            icon = "ui/construction/station/rail/modular_station/high_speed_catenary.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "motras_track",
        order = {
            value = 4,
        },
        metadata = {
            motras_electrified = true,
            motras_highspeed = true,
            motras_toggleElectrificationTo = "station/rail/modules/motras_track_train_high_speed.module",
            motras_toggleHighspeedTo = "station/rail/modules/motras_track_train_normal_catenary.module",
            motras_speedLimit = 300.0 / 3.6,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local track = result.motras:register(slotId)
            TrackModuleUtils.addBasicTrackSlots(track, result.slots)
            
            track:handle(function (moduleResult)
                local snapLeft = not track:getGrid():has(track:getGridX() - 1, track:getGridY())
                local snapRight = not track:getGrid():has(track:getGridX() + 1, track:getGridY())
                TrackModuleUtils.makeTrack(track, 'high_speed.lua', true, snapLeft, snapRight)
            end)
        end,
        getModelsFn = function()
            return { }
        end
    }
end