local Box = require("motras_box")
local Transf = require "transf"
local Vec3 = require "vec3"
local Modulesutil = require "modulesutil"
local UnderpassUtils = require("motras_underpassutils")
local PathUtils = require("motras_pathutils")

function data()
    return {
        cost = {
            price = 0,
        },
        category = {
            categories = { "misc", },
        },
        description = {
            name = _("Passenger underpass"),
            description = _("suitable_for_wide_platforms"),
            icon = "ui/construction/station/rail/motras/underpass_large_era_c.tga"
        },
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "motras_underpass_large",
        order = {
            value = 19022,
        },
        metadata = {
            motras = {
                theme = "era_c",
                themeType = "underpass_large",
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local asset = result.motras:register(slotId, {underpassFloorHeight = -4.8})

            asset:handle(function (moduleResult)
                local stairsTransformation = Transf.mul(transform, Transf.transl(Vec3.new(3, 0, -1)))
            
                local stairsHoleGroundFace = Box:new({-8.0, -4, 0.0}, {3.9, 4, 1.0}):getGroundFace()
                Modulesutil.TransformFaces(transform, stairsHoleGroundFace)
                table.insert(result.groundFaces, {  
                    face = stairsHoleGroundFace,
                    modes = {
                        {
                            type = "FILL",
                            key = "hole.lua"
                        }
                    }
                })

                table.insert(result.models, {
                    id = 'station/rail/motras/stairs_large.mdl',
                    transf = stairsTransformation,
                    tag = tag
                })

                local zOffset = asset:getGrid():getUnderpassZ()- asset:getParentGridElement():getAbsolutePlatformHeight()
                table.insert(result.models, PathUtils.makePassengerPathModel(
                    {x = -12.7, y = -1.5, z = -4.8},
                    {x = -20.0, y = 0.0, z = zOffset},
                    stairsTransformation
                ))
                table.insert(result.models, PathUtils.makePassengerPathModel(
                    {x = -12.7, y = 1.5, z = -4.8},
                    {x = -20.0, y = 0.0, z = zOffset},
                    stairsTransformation
                ))
            end)
        end,
        getModelsFn = function()
            return {
               
            }
        end
    }
end