local Transf = require("transf")

function data()
    return {
        cost = {
            price = 0,
        },
        category = {
            categories = { "decoration", },
        },
        description = {
            name = _("station_clock"),
		    description = _("truss_mountable"),
		    icon = "ui/construction/station/rail/motras/decoration_clock_truss_mounted_era_c.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "motras_decoration_truss_mounted",
        order = {
            value = 59003,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local decoration = result.motras:register(slotId)

            decoration:handle(function ()
                table.insert(result.models, {
                    id = "station/rail/asset/era_c_perron_holder.mdl",
                    transf = transform,
                    tag = tag
                })
                table.insert(result.models, {
                    id = "station/rail/asset/era_c_small_clock.mdl",
                    transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = -0.235, y = -1.16, z = 0.0})),
                    tag = tag
                })
                table.insert(result.models, {
                    id = "station/rail/asset/era_c_small_clock.mdl",
                    transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = -0.235, y = 1.16, z = 0.0})),
                    tag = tag
                })
            end)
        end,
        getModelsFn = function()
            return {
                { 
                    id = "station/rail/asset/era_c_perron_holder.mdl",
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1
                    },
                }, { 
                    id = "station/rail/asset/era_c_small_clock.mdl",
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        -0.235, -1.16, 0, 1
                    },
                }, { 
                    id = "station/rail/asset/era_c_small_clock.mdl",
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        -0.235, 1.16, 0, 1
                    },
                },
            }
        end
    }
end