local PlatformModuleUtils = require('motras_platformmoduleutils')

function data()
    return {
        cost = {
            price = 18000,
        },
        category = {
            categories = { "passenger", },
        },
        description = {
            name = _("platform"),
		    description = _("680mm"),
            icon = "ui/construction/station/rail/motras/platform_680_era_c.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "motras_platform",
        order = {
            value = 10680,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local platform = result.motras:register(slotId, {platformHeight = 0.68})
            PlatformModuleUtils.makePlatformModule(platform, result, transform, tag, slotId, addModelFn, params)
        end,
        getModelsFn = function()
            return { }
        end
    }
end