local Transf = require("transf")
local ModelUtils = require("motras_modelutils")

local function addTopPlatformNumberAndClock(result, transform, label, tag)
    -- clock
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = 0.0, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = 0.7}
        )),
        tag = tag
    })
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = 0.0, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = 0.5}
        )),
        tag = tag
    })
    table.insert(result.models, {
        id = "station/rail/asset/era_c_small_clock.mdl",
        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0.0, y = 1.0, z = 0.6})),
        tag = tag
    })

    --platform number
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = 0.0, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = 0.0}
        )),
        tag = tag
    })
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = 0.0, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = -0.2}
        )),
        tag = tag
    })
    ModelUtils.addLabeledModel(
        result,
        "station/rail/motras/platform_number_sign_era_c.mdl",
        { label, label },
        Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = 0.0, y = 0.7, z = -0.1})),
        tag
    )
end

local function addBottomPlatformNumberAndClock(result, transform, label, tag)
    -- clock
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = math.pi, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = 0.7}
        )),
        tag = tag
    })
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = math.pi, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = 0.5}
        )),
        tag = tag
    })
    table.insert(result.models, {
        id = "station/rail/asset/era_c_small_clock.mdl",
        transf = Transf.mul(transform, Transf.rotZTransl(math.pi / 2, {x = -0.0, y = -1.0, z = 0.6})),
        tag = tag
    })

    --platform number
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = math.pi, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = 0.0}
        )),
        tag = tag
    })
    table.insert(result.models, {
        id = "station/rail/asset/era_c_street_pillar.mdl",
        transf = Transf.mul(transform, Transf.scaleRotZYXTransl(
            {x = 0.5, y = -0.5, z = -1.0},
            {x = math.pi, y = 0.0, z = math.pi / 2},
            {x = 0.0, y = 0.0, z = -0.2}
        )),
        tag = tag
    })
    ModelUtils.addLabeledModel(
        result,
        "station/rail/motras/platform_number_sign_era_c.mdl",
        { label, label },
        Transf.mul(transform, Transf.rotZTransl(-math.pi / 2, {x = 0.0, y = -0.7, z = -0.1})),
        tag
    )
end

function data()
    return {
        cost = {
            price = 10000,
        },
        category = {
            categories = { "decoration", },
        },
        description = {
            name = _("platform_number_sign_and_clock"),
		    description = _("truss_mountable") .. "\n" .. _("suitable_for_curved_roof"),
		    icon = "ui/construction/station/rail/motras/decoration_platform_number_and_clock_truss_mounted_era_c.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "motras_decoration_truss_mounted",
        order = {
            value = 49004,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local decoration = result.motras:register(slotId)

            decoration:handle(function ()
                local gridElement = decoration:getParentGridElement()
                local hasTrackTop = gridElement:getNeighborTop():isTrack()
                local hasTrackBottom = gridElement:getNeighborBottom():isTrack()

                local lableForBottomTrack = ''
                local lableForTopTrack = ''

                if decoration:getAssetId() == 34 or decoration:getAssetId() == 46 then
                    local bottomTrack = gridElement:getGrid():get(decoration:getGridX(), decoration:getGridY() - 2)
                    local topTrack = gridElement:getNeighborTop()

                    if bottomTrack:isTrack() then
                        lableForBottomTrack = bottomTrack:getDisplayedId()
                    end
                    if topTrack:isTrack() then
                        lableForTopTrack = topTrack:getDisplayedId()
                    end
                else
                    local bottomTrack = gridElement:getNeighborBottom()
                    local topTrack = gridElement:getNeighborTop()

                    if bottomTrack:isTrack() then
                        lableForBottomTrack = bottomTrack:getDisplayedId()
                    end
                    if topTrack:isTrack() then
                        lableForTopTrack = topTrack:getDisplayedId()
                    end
                end

                if decoration:getAssetId() == 46 then
                    addTopPlatformNumberAndClock(result, transform, lableForTopTrack, tag)
                    addBottomPlatformNumberAndClock(result, transform, lableForBottomTrack, tag)
                end
                if hasTrackTop and not hasTrackBottom then
                    addTopPlatformNumberAndClock(result, transform, lableForTopTrack, tag)
                elseif hasTrackBottom and not hasTrackTop then
                    addBottomPlatformNumberAndClock(result, transform, lableForBottomTrack, tag)
                else
                    addTopPlatformNumberAndClock(result, transform, lableForTopTrack, tag)
                    addBottomPlatformNumberAndClock(result, transform, lableForBottomTrack, tag)
                end
            end)
        end,
        getModelsFn = function()
            return {
                {
                    id = "station/rail/asset/era_c_small_clock.mdl",
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 1.0, 0.6, 1
                    },
                }, { 
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = {
                        0.5, 0, 0, 0,
                        0, 0, -0.5, 0,
                        0, 1, 0, 0,
                        0, 0, 0.7, 1
                    },
                }, { 
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = {
                        0.5, 0, 0, 0,
                        0, 0, -0.5, 0,
                        0, 1, 0, 0,
                        0, 0, 0.5, 1
                    },
                }, 
                -- platform number
                { 
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = {
                        0.5, 0, 0, 0,
                        0, 0, -0.5, 0,
                        0, 1, 0, 0,
                        0, 0, 0.0, 1
                    },
                }, { 
                    id = "station/rail/asset/era_c_street_pillar.mdl",
                    transf = {
                        0.5, 0, 0, 0,
                        0, 0, -0.5, 0,
                        0, 1, 0, 0,
                        0, 0, -0.2, 1
                    },
                }, { 
                    id = "station/rail/motras/platform_number_sign_era_c.mdl",
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0.7, -0.1, 1
                    },
                },
            }
        end
    }
end