local PlatformModuleUtils = require('motras_platformmoduleutils')
local t = require('motras_types')
local Box = require('motras_box')
local Transf = require('transf')

function data()
    return {
        cost = {
            price = 18000,
        },
        category = {
            categories = { "passenger", },
        },
        description = {
            name = _("platform_270"),
		    description = _("platform_270_desc"),
            icon = "ui/construction/station/rail/modular_station/track.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "motras_platform",
        order = {
            value = 1,
        },
        metadata = {
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local platform = result.motras:register(slotId, {platformHeight = 0.27})
            PlatformModuleUtils.addBuildingSlotsFor40mPlatform(platform, result.slots)
            PlatformModuleUtils.addUnderpassSlots(platform, result.slots)

            platform:handle(function (moduleResult)
                local boundingBox = Box:new(
                    {platform:getAbsoluteX() - 20, platform:getAbsoluteY() - 2.5, 0},
                    {platform:getAbsoluteX() + 20, platform:getAbsoluteY() + 2.5, platform:getAbsolutePlatformHeight()}
                )

                table.insert(result.terrainAlignmentLists, { type = "EQUAL", faces = { boundingBox:getGroundFace() } })

                local platformRep = PlatformModuleUtils.makePlatformSurfaceWithUnderpathHoles(platform, {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    platform:getAbsoluteX(), platform:getAbsoluteY(), platform:getAbsolutePlatformHeight(), 1
                }, 'station/rail/motras/platform_stairs_main.mdl'):addOuterLeftSegment(
                    'station/rail/motras/platform_stairs_1_1.mdl', 'station/rail/motras/platform_stairs_1_2.mdl', 'station/rail/motras/platform_stairs_1_3.mdl', 'station/rail/motras/platform_stairs_1_4.mdl'
                ):addInnerLeftSegment(
                    'station/rail/motras/platform_stairs_2_1.mdl', 'station/rail/motras/platform_stairs_2_2.mdl', 'station/rail/motras/platform_stairs_2_3.mdl', 'station/rail/motras/platform_stairs_2_4.mdl'
                ):addInnerRightSegment(
                    'station/rail/motras/platform_stairs_3_1.mdl', 'station/rail/motras/platform_stairs_3_2.mdl', 'station/rail/motras/platform_stairs_3_3.mdl', 'station/rail/motras/platform_stairs_3_4.mdl'
                ):addOuterRightSegment(
                    'station/rail/motras/platform_stairs_4_1.mdl', 'station/rail/motras/platform_stairs_4_2.mdl', 'station/rail/motras/platform_stairs_4_3.mdl', 'station/rail/motras/platform_stairs_4_4.mdl'
                )

                PlatformModuleUtils.makePlatform(
                    platform,
                    result.models,
                    platformRep,
                    'station/rail/motras/platform_edge_rep.mdl',
                    'station/rail/motras/platform_back_rep.mdl',
                    'station/rail/motras/platform_side.mdl',
                    'station/rail/motras/platform_edge_side_left.mdl',
                    'station/rail/motras/platform_edge_side_right.mdl',
                    'station/rail/motras/platform_back_side_left.mdl',
                    'station/rail/motras/platform_back_side_right.mdl',
                    { addBackEdgesOnConnect = true }
                )
            end)
            
            platform:handleTerminals(function (addTerminal, directionFactor)
                local passengerTerminalModel = 'station/rail/motras/path/passenger_terminal_10m.mdl'
                local hasNoTrackOnOppositeSide = not platform:getGrid():get(platform:getGridX(), platform:getGridY() - directionFactor):isTrack()

                if not platform:hasAsset(25) then
                    addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = -15, y =  1.5 * directionFactor}, directionFactor), 0)
                    if hasNoTrackOnOppositeSide then
                        addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = -15, y =  -1.5 * directionFactor}, directionFactor), 0)
                    end
                end
                if not platform:hasAsset(26) then
                    addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = -5, y =  1.5 * directionFactor}, directionFactor), 0)
                    if hasNoTrackOnOppositeSide then
                        addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = -5, y =  -1.5 * directionFactor}, directionFactor), 0)
                    end
                end
                if not platform:hasAsset(27) then
                    addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = 5, y =  1.5 * directionFactor}, directionFactor), 0)
                    if hasNoTrackOnOppositeSide then
                        addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = 5, y =  -1.5 * directionFactor}, directionFactor), 0)
                    end
                end
                if not platform:hasAsset(28) then
                    addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = 15, y =  1.5 * directionFactor}, directionFactor), 0)
                    if hasNoTrackOnOppositeSide then
                        addTerminal(passengerTerminalModel, platform:getGlobalTransformationBasedOnPlatformTop({x = 15, y =  -1.5 * directionFactor}, directionFactor), 0)
                    end
                end
            end)
        end,
        getModelsFn = function()
            return { }
        end
    }
end