local Transf = require('transf')
local t = require('motras_types')

function data()
    return {
        availability = {
            yearFrom = 1980,
            yearTo = 0,
        },
        cost = {
            price = 0,
        },
        category = {
            categories = { "misc", },
        },
        description = {
            name = _("Platform roof"),
            description = _("Decorative.\nRoof for passenger platforms."),
            icon = "ui/construction/station/rail/modular_station/platform_passenger_roof_era_c.tga"
        },
        -- buildMode = "MULTI",
        type = "motras_roof_small",
        order = {
            value = 29020,
        },
        metadata = {
            platform_roof = true,
            motras = {
                poleRadius = 0.17,
                theme = "era_c",
                themeType = "roof",
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local asset = result.motras:register(slotId)

            asset:addDecorationSlot(result.slots, 1, {
                position = {-20.0, 2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            asset:addDecorationSlot(result.slots, 2, {
                position = {-20.0, -2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                rotation = 180,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            asset:addDecorationSlot(result.slots, 3, {
                position = {-10.0, 2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            asset:addDecorationSlot(result.slots, 4, {
                position = {-10.0, -2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                rotation = 180,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            asset:addDecorationSlot(result.slots, 5, {
                position = {0.0, 2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            asset:addDecorationSlot(result.slots, 6, {
                position = {0.0, -2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                rotation = 180,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            asset:addDecorationSlot(result.slots, 7, {
                position = {10.0, 2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            asset:addDecorationSlot(result.slots, 8, {
                position = {10.0, -2, -1.4},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                rotation = 180,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })
            local leftNeighbor = asset:getParentGridElement():getNeighborRight()
            if not (leftNeighbor:isPlatform() and leftNeighbor:hasAsset(33)) then
                asset:addDecorationSlot(result.slots, 9, {
                    assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                    position = {20.0, 2, -1.4},
                    slotType = 'motras_decoration_ceiling_mounted',
                    transformation = transform,
                    spacing = {1.0, 1.0, 1.0, 1.0}
                })
                asset:addDecorationSlot(result.slots, 10, {
                    assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                    position = {20.0, -2, -1.4},
                    slotType = 'motras_decoration_ceiling_mounted',
                    transformation = transform,
                    rotation = 180,
                    spacing = {1.0, 1.0, 1.0, 1.0}
                })
            end

            asset:addDecorationSlot(result.slots, 11, {
                position = {-15.0, 0, -2.2},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            asset:addDecorationSlot(result.slots, 12, {
                position = {-5.0, 0, -2.2},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            asset:addDecorationSlot(result.slots, 13, {
                position = {5.0, 0, -2.2},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            asset:addDecorationSlot(result.slots, 14, {
                position = {15.0, 0, -2.2},
                assetDecorationType = t.ASSET_DECORATION_CEILING_MOUNTED,
                slotType = 'motras_decoration_ceiling_mounted',
                transformation = transform,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            asset:addDecorationSlot(result.slots, 1, {
                position = {-20.0, 0.0, -2.4},
                assetDecorationType = t.ASSET_DECORATION_TRUSS_MOUNTED,
                slotType = 'motras_decoration_truss_mounted',
                transformation = transform,
                rotation = 0,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            asset:addDecorationSlot(result.slots, 2, {
                position = {-10.0, 0.0, -2.4},
                assetDecorationType = t.ASSET_DECORATION_TRUSS_MOUNTED,
                slotType = 'motras_decoration_truss_mounted',
                transformation = transform,
                rotation = 0,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            asset:addDecorationSlot(result.slots, 3, {
                position = {0.0, 0.0, -2.4},
                assetDecorationType = t.ASSET_DECORATION_TRUSS_MOUNTED,
                slotType = 'motras_decoration_truss_mounted',
                transformation = transform,
                rotation = 0,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            asset:addDecorationSlot(result.slots, 4, {
                position = {10.0, 0.0, -2.4},
                assetDecorationType = t.ASSET_DECORATION_TRUSS_MOUNTED,
                slotType = 'motras_decoration_truss_mounted',
                transformation = transform,
                rotation = 0,
                spacing = {1.0, 1.0, 1.0, 1.0}
            })

            if not (leftNeighbor:isPlatform() and leftNeighbor:hasAsset(33)) then
                asset:addDecorationSlot(result.slots, 5, {
                    position = {20.0, 0.0, -2.4},
                    assetDecorationType = t.ASSET_DECORATION_TRUSS_MOUNTED,
                    slotType = 'motras_decoration_truss_mounted',
                    transformation = transform,
                    rotation = 0,
                    spacing = {1.0, 1.0, 1.0, 1.0}
                })
            end


            asset:handle(function ()
                local roofTransformation = Transf.mul(transform, Transf.transl({x = -20, y = 0, z = -6}))

                table.insert(result.models, {
                    id = "station/rail/era_c/perron_5_roof.mdl",
                    transf = roofTransformation,
                    tag = tag
                })

                if not asset:getParentGridElement():getNeighborLeft():hasAsset(33) then
                    table.insert(result.models, {
                        id = "station/rail/era_c/perron_5_roof_end.mdl",
                        transf = Transf.mul(roofTransformation, Transf.rotZTransl(math.rad(-180), {x = 0, y = 0, z = 0})),
                        tag = tag
                    })
                end

                if not asset:getParentGridElement():getNeighborRight():hasAsset(33) then
                    table.insert(result.models, {
                        id = "station/rail/era_c/perron_5_roof_end.mdl",
                        transf = Transf.mul(roofTransformation, Transf.transl({x = 40, y = 0, z = 0})),
                        tag = tag
                    })
                end
            end)
        end,
        getModelsFn = function()
            return { }
        end
    }
end