return {
    GRID_MAX_XY_POSITION = 63,
    DEFAULT_VERTICAL_GRID_DISTANCE = 5,
    DEFAULT_HORIZONTAL_GRID_DISTANCE = 40,
    DEFAULT_MODULE_PREFIX = 'motras',
    DEFAULT_BASE_HEIGHT = 0,
    DEFAULT_CUSTOM_TRACK_TYPE = 'standard.lua',
    DEFAULT_MODULE_TRACK_TYPE = 'standard.lua',
    DEFAULT_PLATFORM_HEIGHT = 0.55,
    DEFAULT_BASE_TRACK_HEIGHT = 0.53,
    DEFAULT_PLATFORM_WAITING_EDGE_OFFSET = 1.5,
    DEFAULT_PASSENGER_TERMINAL_MODEL = 'station/rail/motras/path/passenger_terminal_40m.mdl',
    DEFAULT_ASSET_SLOT_SPACING = {0.1, 0.1, 0.1, 0.1},
    BUILDING_PLATFORM40M_SMALL_SPACING = { 5, 5, 10, 5},
    BUILDING_PLATFORM40M_MEDIUM_SPACING = { 10, 10, 10, 5},
    BUILDING_PLATFORM40M_LARGE_SPACING = { 20, 20, 10, 5}
}